---
ID: "c920dbef-8bac-4f41-87c6-99571ed7dda6"
Parent: "aea91936-870e-40df-b18a-0e949c0ad3d6"
Template: "aea91936-870e-40df-b18a-0e949c0ad3d6"
Path: /sitecore/templates/eContracting2/Pages/Disclaimer/__Standard Values
DB: master
SharedFields:
- ID: "f1a1fe9e-a60c-4ddb-a3a0-bb5b29fe732e"
  Hint: __Renderings
  Type: layout
  Value: |
    <r xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <d
        id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}"
        l="{37DC70FC-BEB9-4179-9FCC-F2E35CC61BCA}">
        <r
          id="{43E8A867-8481-4FFC-AE4A-4230DD7ADFE7}"
          ph="eContracting2"
          uid="{806A21BC-26CC-4AC4-B0DF-8728D1E0F2C6}" />
      </d>
    </r>
Languages:
- Language: cs
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20201007T125255Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20161006T115532Z
