---
ID: "1e99a256-c63e-43f2-a71a-de28f22a0e46"
Parent: "4f3b54ba-3dbc-408c-9573-f9f86ac0c3c7"
Template: "4f3b54ba-3dbc-408c-9573-f9f86ac0c3c7"
Path: /sitecore/templates/eContracting2/Pages/Thank You/__Standard Values
DB: master
SharedFields:
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 300
Languages:
- Language: cs
  Versions:
  - Version: 1
    Fields:
    - ID: "04bf00db-f5fb-41f7-8ab7-22408372a981"
      Hint: __Final Renderings
      Type: Layout
      Value: |
        <r xmlns:p="p" xmlns:s="s"
          p:p="1">
          <d
            id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}">
            <r
              uid="{D5229F29-973F-4F93-B9CB-46EBD008B4BD}"
              p:after="r[@uid='{0B8EA37E-00C7-47C9-9562-C070E573E9A0}']"
              s:id="{5E67F4C6-DAFB-469B-B6D5-7E5C4837E96B}"
              s:ph="eContracting2Main" />
            <r
              uid="{1F951A91-EBBA-4F44-8AC8-7319772D5BB2}"
              p:after="*[1=2]" />
          </d>
        </r>
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200422T090319Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
