---
ID: "362e8f1c-7c7b-4b60-9c1c-aaa889869be8"
Parent: "756508d8-3e1a-45a8-8ec3-f450356f6d32"
Template: "756508d8-3e1a-45a8-8ec3-f450356f6d32"
Path: /sitecore/templates/eContracting2/Datasources/Buttons Folder/__Standard Values
DB: master
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Type: TreelistEx
  Value: "{14111589-96E4-449E-AE4A-3ED3EFB48480}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20220126T125549Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
