---
ID: "dad2210b-70aa-4a0a-aa44-5c07390f9e73"
Parent: "5b43aa17-1f2e-4c54-b695-83a1a40a9f1b"
Template: "e269fbb5-3750-427a-9149-7aa950b49301"
Path: /sitecore/templates/eContracting/SiteRoot/Login Settings
DB: master
SharedFields:
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 200
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190108T120613Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
