//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eContracting.Services.SAP {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", ConfigurationName="SAP.ZCCH_CACHE_API")]
    internal interface ZCCH_CACHE_API {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:sap-com:document:sap:rfc:functions:ZCCH_CACHE_API:ZCCH_CACHE_GETRequest", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        eContracting.Services.SAP.ZCCH_CACHE_GETResponse1 ZCCH_CACHE_GET(eContracting.Services.SAP.ZCCH_CACHE_GETRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:sap-com:document:sap:rfc:functions:ZCCH_CACHE_API:ZCCH_CACHE_GETRequest", ReplyAction="*")]
        System.Threading.Tasks.Task<eContracting.Services.SAP.ZCCH_CACHE_GETResponse1> ZCCH_CACHE_GETAsync(eContracting.Services.SAP.ZCCH_CACHE_GETRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:sap-com:document:sap:rfc:functions:ZCCH_CACHE_API:ZCCH_CACHE_DELRequest", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        eContracting.Services.SAP.ZCCH_CACHE_DELResponse1 ZCCH_CACHE_DEL(eContracting.Services.SAP.ZCCH_CACHE_DELRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:sap-com:document:sap:rfc:functions:ZCCH_CACHE_API:ZCCH_CACHE_DELRequest", ReplyAction="*")]
        System.Threading.Tasks.Task<eContracting.Services.SAP.ZCCH_CACHE_DELResponse1> ZCCH_CACHE_DELAsync(eContracting.Services.SAP.ZCCH_CACHE_DELRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:sap-com:document:sap:rfc:functions:ZCCH_CACHE_API:ZCCH_CACHE_STATUS_SETReques" +
            "t", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        eContracting.Services.SAP.ZCCH_CACHE_STATUS_SETResponse1 ZCCH_CACHE_STATUS_SET(eContracting.Services.SAP.ZCCH_CACHE_STATUS_SETRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:sap-com:document:sap:rfc:functions:ZCCH_CACHE_API:ZCCH_CACHE_STATUS_SETReques" +
            "t", ReplyAction="*")]
        System.Threading.Tasks.Task<eContracting.Services.SAP.ZCCH_CACHE_STATUS_SETResponse1> ZCCH_CACHE_STATUS_SETAsync(eContracting.Services.SAP.ZCCH_CACHE_STATUS_SETRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:sap-com:document:sap:rfc:functions:ZCCH_CACHE_API:ZCCH_CACHE_PUTRequest", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        eContracting.Services.SAP.ZCCH_CACHE_PUTResponse1 ZCCH_CACHE_PUT(eContracting.Services.SAP.ZCCH_CACHE_PUTRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:sap-com:document:sap:rfc:functions:ZCCH_CACHE_API:ZCCH_CACHE_PUTRequest", ReplyAction="*")]
        System.Threading.Tasks.Task<eContracting.Services.SAP.ZCCH_CACHE_PUTResponse1> ZCCH_CACHE_PUTAsync(eContracting.Services.SAP.ZCCH_CACHE_PUTRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZCCH_CACHE_GET : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string iV_CCHKEYField;
        
        private string iV_CCHTYPEField;
        
        private string iV_GEFILEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string IV_CCHKEY {
            get {
                return this.iV_CCHKEYField;
            }
            set {
                this.iV_CCHKEYField = value;
                this.RaisePropertyChanged("IV_CCHKEY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string IV_CCHTYPE {
            get {
                return this.iV_CCHTYPEField;
            }
            set {
                this.iV_CCHTYPEField = value;
                this.RaisePropertyChanged("IV_CCHTYPE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string IV_GEFILE {
            get {
                return this.iV_GEFILEField;
            }
            set {
                this.iV_GEFILEField = value;
                this.RaisePropertyChanged("IV_GEFILE");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class BAPIRET2 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tYPEField;
        
        private string idField;
        
        private string nUMBERField;
        
        private string mESSAGEField;
        
        private string lOG_NOField;
        
        private string lOG_MSG_NOField;
        
        private string mESSAGE_V1Field;
        
        private string mESSAGE_V2Field;
        
        private string mESSAGE_V3Field;
        
        private string mESSAGE_V4Field;
        
        private string pARAMETERField;
        
        private int rOWField;
        
        private string fIELDField;
        
        private string sYSTEMField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string TYPE {
            get {
                return this.tYPEField;
            }
            set {
                this.tYPEField = value;
                this.RaisePropertyChanged("TYPE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string NUMBER {
            get {
                return this.nUMBERField;
            }
            set {
                this.nUMBERField = value;
                this.RaisePropertyChanged("NUMBER");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string MESSAGE {
            get {
                return this.mESSAGEField;
            }
            set {
                this.mESSAGEField = value;
                this.RaisePropertyChanged("MESSAGE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string LOG_NO {
            get {
                return this.lOG_NOField;
            }
            set {
                this.lOG_NOField = value;
                this.RaisePropertyChanged("LOG_NO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string LOG_MSG_NO {
            get {
                return this.lOG_MSG_NOField;
            }
            set {
                this.lOG_MSG_NOField = value;
                this.RaisePropertyChanged("LOG_MSG_NO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string MESSAGE_V1 {
            get {
                return this.mESSAGE_V1Field;
            }
            set {
                this.mESSAGE_V1Field = value;
                this.RaisePropertyChanged("MESSAGE_V1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string MESSAGE_V2 {
            get {
                return this.mESSAGE_V2Field;
            }
            set {
                this.mESSAGE_V2Field = value;
                this.RaisePropertyChanged("MESSAGE_V2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string MESSAGE_V3 {
            get {
                return this.mESSAGE_V3Field;
            }
            set {
                this.mESSAGE_V3Field = value;
                this.RaisePropertyChanged("MESSAGE_V3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string MESSAGE_V4 {
            get {
                return this.mESSAGE_V4Field;
            }
            set {
                this.mESSAGE_V4Field = value;
                this.RaisePropertyChanged("MESSAGE_V4");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string PARAMETER {
            get {
                return this.pARAMETERField;
            }
            set {
                this.pARAMETERField = value;
                this.RaisePropertyChanged("PARAMETER");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public int ROW {
            get {
                return this.rOWField;
            }
            set {
                this.rOWField = value;
                this.RaisePropertyChanged("ROW");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string FIELD {
            get {
                return this.fIELDField;
            }
            set {
                this.fIELDField = value;
                this.RaisePropertyChanged("FIELD");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string SYSTEM {
            get {
                return this.sYSTEMField;
            }
            set {
                this.sYSTEMField = value;
                this.RaisePropertyChanged("SYSTEM");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZCCH_ST_FILE : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string fILEINDXField;
        
        private string fILENAMEField;
        
        private string mIMETYPEField;
        
        private byte[] fILECONTENTField;
        
        private ZCCH_ST_ATTRIB[] aTTRIBField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string FILEINDX {
            get {
                return this.fILEINDXField;
            }
            set {
                this.fILEINDXField = value;
                this.RaisePropertyChanged("FILEINDX");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string FILENAME {
            get {
                return this.fILENAMEField;
            }
            set {
                this.fILENAMEField = value;
                this.RaisePropertyChanged("FILENAME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string MIMETYPE {
            get {
                return this.mIMETYPEField;
            }
            set {
                this.mIMETYPEField = value;
                this.RaisePropertyChanged("MIMETYPE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=3)]
        public byte[] FILECONTENT {
            get {
                return this.fILECONTENTField;
            }
            set {
                this.fILECONTENTField = value;
                this.RaisePropertyChanged("FILECONTENT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZCCH_ST_ATTRIB[] ATTRIB {
            get {
                return this.aTTRIBField;
            }
            set {
                this.aTTRIBField = value;
                this.RaisePropertyChanged("ATTRIB");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZCCH_ST_ATTRIB : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string aTTRIDField;
        
        private string aTTRINDXField;
        
        private string aTTRVALField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string ATTRID {
            get {
                return this.aTTRIDField;
            }
            set {
                this.aTTRIDField = value;
                this.RaisePropertyChanged("ATTRID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string ATTRINDX {
            get {
                return this.aTTRINDXField;
            }
            set {
                this.aTTRINDXField = value;
                this.RaisePropertyChanged("ATTRINDX");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string ATTRVAL {
            get {
                return this.aTTRVALField;
            }
            set {
                this.aTTRVALField = value;
                this.RaisePropertyChanged("ATTRVAL");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZCCH_ST_HEADER : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string cCHTYPEField;
        
        private string cCHKEYField;
        
        private string cCHSTATField;
        
        private string cCHVALTOField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string CCHTYPE {
            get {
                return this.cCHTYPEField;
            }
            set {
                this.cCHTYPEField = value;
                this.RaisePropertyChanged("CCHTYPE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string CCHKEY {
            get {
                return this.cCHKEYField;
            }
            set {
                this.cCHKEYField = value;
                this.RaisePropertyChanged("CCHKEY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string CCHSTAT {
            get {
                return this.cCHSTATField;
            }
            set {
                this.cCHSTATField = value;
                this.RaisePropertyChanged("CCHSTAT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string CCHVALTO {
            get {
                return this.cCHVALTOField;
            }
            set {
                this.cCHVALTOField = value;
                this.RaisePropertyChanged("CCHVALTO");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZCCH_CACHE_GETResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ZCCH_ST_HEADER eS_HEADERField;
        
        private ZCCH_ST_ATTRIB[] eT_ATTRIBField;
        
        private ZCCH_ST_FILE[] eT_FILESField;
        
        private BAPIRET2[] eT_RETURNField;
        
        private int eV_RETCODEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ZCCH_ST_HEADER ES_HEADER {
            get {
                return this.eS_HEADERField;
            }
            set {
                this.eS_HEADERField = value;
                this.RaisePropertyChanged("ES_HEADER");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZCCH_ST_ATTRIB[] ET_ATTRIB {
            get {
                return this.eT_ATTRIBField;
            }
            set {
                this.eT_ATTRIBField = value;
                this.RaisePropertyChanged("ET_ATTRIB");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZCCH_ST_FILE[] ET_FILES {
            get {
                return this.eT_FILESField;
            }
            set {
                this.eT_FILESField = value;
                this.RaisePropertyChanged("ET_FILES");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public BAPIRET2[] ET_RETURN {
            get {
                return this.eT_RETURNField;
            }
            set {
                this.eT_RETURNField = value;
                this.RaisePropertyChanged("ET_RETURN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int EV_RETCODE {
            get {
                return this.eV_RETCODEField;
            }
            set {
                this.eV_RETCODEField = value;
                this.RaisePropertyChanged("EV_RETCODE");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class ZCCH_CACHE_GETRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        public eContracting.Services.SAP.ZCCH_CACHE_GET ZCCH_CACHE_GET;
        
        public ZCCH_CACHE_GETRequest() {
        }
        
        public ZCCH_CACHE_GETRequest(eContracting.Services.SAP.ZCCH_CACHE_GET ZCCH_CACHE_GET) {
            this.ZCCH_CACHE_GET = ZCCH_CACHE_GET;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class ZCCH_CACHE_GETResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        public eContracting.Services.SAP.ZCCH_CACHE_GETResponse ZCCH_CACHE_GETResponse;
        
        public ZCCH_CACHE_GETResponse1() {
        }
        
        public ZCCH_CACHE_GETResponse1(eContracting.Services.SAP.ZCCH_CACHE_GETResponse ZCCH_CACHE_GETResponse) {
            this.ZCCH_CACHE_GETResponse = ZCCH_CACHE_GETResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZCCH_CACHE_DEL : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string iV_CCHKEYField;
        
        private string iV_CCHTYPEField;
        
        private string iV_COMMITField;
        
        private string iV_DEL_FILESField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string IV_CCHKEY {
            get {
                return this.iV_CCHKEYField;
            }
            set {
                this.iV_CCHKEYField = value;
                this.RaisePropertyChanged("IV_CCHKEY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string IV_CCHTYPE {
            get {
                return this.iV_CCHTYPEField;
            }
            set {
                this.iV_CCHTYPEField = value;
                this.RaisePropertyChanged("IV_CCHTYPE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string IV_COMMIT {
            get {
                return this.iV_COMMITField;
            }
            set {
                this.iV_COMMITField = value;
                this.RaisePropertyChanged("IV_COMMIT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string IV_DEL_FILES {
            get {
                return this.iV_DEL_FILESField;
            }
            set {
                this.iV_DEL_FILESField = value;
                this.RaisePropertyChanged("IV_DEL_FILES");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZCCH_CACHE_DELResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private BAPIRET2[] eT_RETURNField;
        
        private int eV_RETCODEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public BAPIRET2[] ET_RETURN {
            get {
                return this.eT_RETURNField;
            }
            set {
                this.eT_RETURNField = value;
                this.RaisePropertyChanged("ET_RETURN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int EV_RETCODE {
            get {
                return this.eV_RETCODEField;
            }
            set {
                this.eV_RETCODEField = value;
                this.RaisePropertyChanged("EV_RETCODE");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class ZCCH_CACHE_DELRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        public eContracting.Services.SAP.ZCCH_CACHE_DEL ZCCH_CACHE_DEL;
        
        public ZCCH_CACHE_DELRequest() {
        }
        
        public ZCCH_CACHE_DELRequest(eContracting.Services.SAP.ZCCH_CACHE_DEL ZCCH_CACHE_DEL) {
            this.ZCCH_CACHE_DEL = ZCCH_CACHE_DEL;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class ZCCH_CACHE_DELResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        public eContracting.Services.SAP.ZCCH_CACHE_DELResponse ZCCH_CACHE_DELResponse;
        
        public ZCCH_CACHE_DELResponse1() {
        }
        
        public ZCCH_CACHE_DELResponse1(eContracting.Services.SAP.ZCCH_CACHE_DELResponse ZCCH_CACHE_DELResponse) {
            this.ZCCH_CACHE_DELResponse = ZCCH_CACHE_DELResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZCCH_CACHE_STATUS_SET : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string iV_CCHKEYField;
        
        private string iV_CCHTYPEField;
        
        private string iV_COMMITField;
        
        private string iV_STATField;
        
        private decimal iV_TIMESTAMPField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string IV_CCHKEY {
            get {
                return this.iV_CCHKEYField;
            }
            set {
                this.iV_CCHKEYField = value;
                this.RaisePropertyChanged("IV_CCHKEY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string IV_CCHTYPE {
            get {
                return this.iV_CCHTYPEField;
            }
            set {
                this.iV_CCHTYPEField = value;
                this.RaisePropertyChanged("IV_CCHTYPE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string IV_COMMIT {
            get {
                return this.iV_COMMITField;
            }
            set {
                this.iV_COMMITField = value;
                this.RaisePropertyChanged("IV_COMMIT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string IV_STAT {
            get {
                return this.iV_STATField;
            }
            set {
                this.iV_STATField = value;
                this.RaisePropertyChanged("IV_STAT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public decimal IV_TIMESTAMP {
            get {
                return this.iV_TIMESTAMPField;
            }
            set {
                this.iV_TIMESTAMPField = value;
                this.RaisePropertyChanged("IV_TIMESTAMP");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZCCH_CACHE_STATUS_SETResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private BAPIRET2[] eT_RETURNField;
        
        private int eV_RETCODEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public BAPIRET2[] ET_RETURN {
            get {
                return this.eT_RETURNField;
            }
            set {
                this.eT_RETURNField = value;
                this.RaisePropertyChanged("ET_RETURN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int EV_RETCODE {
            get {
                return this.eV_RETCODEField;
            }
            set {
                this.eV_RETCODEField = value;
                this.RaisePropertyChanged("EV_RETCODE");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class ZCCH_CACHE_STATUS_SETRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        public eContracting.Services.SAP.ZCCH_CACHE_STATUS_SET ZCCH_CACHE_STATUS_SET;
        
        public ZCCH_CACHE_STATUS_SETRequest() {
        }
        
        public ZCCH_CACHE_STATUS_SETRequest(eContracting.Services.SAP.ZCCH_CACHE_STATUS_SET ZCCH_CACHE_STATUS_SET) {
            this.ZCCH_CACHE_STATUS_SET = ZCCH_CACHE_STATUS_SET;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class ZCCH_CACHE_STATUS_SETResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        public eContracting.Services.SAP.ZCCH_CACHE_STATUS_SETResponse ZCCH_CACHE_STATUS_SETResponse;
        
        public ZCCH_CACHE_STATUS_SETResponse1() {
        }
        
        public ZCCH_CACHE_STATUS_SETResponse1(eContracting.Services.SAP.ZCCH_CACHE_STATUS_SETResponse ZCCH_CACHE_STATUS_SETResponse) {
            this.ZCCH_CACHE_STATUS_SETResponse = ZCCH_CACHE_STATUS_SETResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZCCH_CACHE_PUT : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ZCCH_ST_ATTRIB[] iT_ATTRIBField;
        
        private ZCCH_ST_FILE[] iT_FILESField;
        
        private string iV_CCHKEYField;
        
        private string iV_CCHTYPEField;
        
        private string iV_COMMITField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZCCH_ST_ATTRIB[] IT_ATTRIB {
            get {
                return this.iT_ATTRIBField;
            }
            set {
                this.iT_ATTRIBField = value;
                this.RaisePropertyChanged("IT_ATTRIB");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZCCH_ST_FILE[] IT_FILES {
            get {
                return this.iT_FILESField;
            }
            set {
                this.iT_FILESField = value;
                this.RaisePropertyChanged("IT_FILES");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string IV_CCHKEY {
            get {
                return this.iV_CCHKEYField;
            }
            set {
                this.iV_CCHKEYField = value;
                this.RaisePropertyChanged("IV_CCHKEY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string IV_CCHTYPE {
            get {
                return this.iV_CCHTYPEField;
            }
            set {
                this.iV_CCHTYPEField = value;
                this.RaisePropertyChanged("IV_CCHTYPE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string IV_COMMIT {
            get {
                return this.iV_COMMITField;
            }
            set {
                this.iV_COMMITField = value;
                this.RaisePropertyChanged("IV_COMMIT");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZCCH_CACHE_PUTResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ZCCH_ST_ATTRIB[] eT_ATTRIBField;
        
        private ZCCH_ST_FILE[] eT_FILESField;
        
        private BAPIRET2[] eT_RETURNField;
        
        private int eV_RETCODEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZCCH_ST_ATTRIB[] ET_ATTRIB {
            get {
                return this.eT_ATTRIBField;
            }
            set {
                this.eT_ATTRIBField = value;
                this.RaisePropertyChanged("ET_ATTRIB");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZCCH_ST_FILE[] ET_FILES {
            get {
                return this.eT_FILESField;
            }
            set {
                this.eT_FILESField = value;
                this.RaisePropertyChanged("ET_FILES");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public BAPIRET2[] ET_RETURN {
            get {
                return this.eT_RETURNField;
            }
            set {
                this.eT_RETURNField = value;
                this.RaisePropertyChanged("ET_RETURN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int EV_RETCODE {
            get {
                return this.eV_RETCODEField;
            }
            set {
                this.eV_RETCODEField = value;
                this.RaisePropertyChanged("EV_RETCODE");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class ZCCH_CACHE_PUTRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        public eContracting.Services.SAP.ZCCH_CACHE_PUT ZCCH_CACHE_PUT;
        
        public ZCCH_CACHE_PUTRequest() {
        }
        
        public ZCCH_CACHE_PUTRequest(eContracting.Services.SAP.ZCCH_CACHE_PUT ZCCH_CACHE_PUT) {
            this.ZCCH_CACHE_PUT = ZCCH_CACHE_PUT;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    internal partial class ZCCH_CACHE_PUTResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        public eContracting.Services.SAP.ZCCH_CACHE_PUTResponse ZCCH_CACHE_PUTResponse;
        
        public ZCCH_CACHE_PUTResponse1() {
        }
        
        public ZCCH_CACHE_PUTResponse1(eContracting.Services.SAP.ZCCH_CACHE_PUTResponse ZCCH_CACHE_PUTResponse) {
            this.ZCCH_CACHE_PUTResponse = ZCCH_CACHE_PUTResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    internal interface ZCCH_CACHE_APIChannel : eContracting.Services.SAP.ZCCH_CACHE_API, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    internal partial class ZCCH_CACHE_APIClient : System.ServiceModel.ClientBase<eContracting.Services.SAP.ZCCH_CACHE_API>, eContracting.Services.SAP.ZCCH_CACHE_API {
        
        public ZCCH_CACHE_APIClient() {
        }
        
        public ZCCH_CACHE_APIClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ZCCH_CACHE_APIClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ZCCH_CACHE_APIClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ZCCH_CACHE_APIClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public eContracting.Services.SAP.ZCCH_CACHE_GETResponse1 ZCCH_CACHE_GET(eContracting.Services.SAP.ZCCH_CACHE_GETRequest request) {
            return base.Channel.ZCCH_CACHE_GET(request);
        }
        
        public System.Threading.Tasks.Task<eContracting.Services.SAP.ZCCH_CACHE_GETResponse1> ZCCH_CACHE_GETAsync(eContracting.Services.SAP.ZCCH_CACHE_GETRequest request) {
            return base.Channel.ZCCH_CACHE_GETAsync(request);
        }
        
        public eContracting.Services.SAP.ZCCH_CACHE_DELResponse1 ZCCH_CACHE_DEL(eContracting.Services.SAP.ZCCH_CACHE_DELRequest request) {
            return base.Channel.ZCCH_CACHE_DEL(request);
        }
        
        public System.Threading.Tasks.Task<eContracting.Services.SAP.ZCCH_CACHE_DELResponse1> ZCCH_CACHE_DELAsync(eContracting.Services.SAP.ZCCH_CACHE_DELRequest request) {
            return base.Channel.ZCCH_CACHE_DELAsync(request);
        }
        
        public eContracting.Services.SAP.ZCCH_CACHE_STATUS_SETResponse1 ZCCH_CACHE_STATUS_SET(eContracting.Services.SAP.ZCCH_CACHE_STATUS_SETRequest request) {
            return base.Channel.ZCCH_CACHE_STATUS_SET(request);
        }
        
        public System.Threading.Tasks.Task<eContracting.Services.SAP.ZCCH_CACHE_STATUS_SETResponse1> ZCCH_CACHE_STATUS_SETAsync(eContracting.Services.SAP.ZCCH_CACHE_STATUS_SETRequest request) {
            return base.Channel.ZCCH_CACHE_STATUS_SETAsync(request);
        }
        
        public eContracting.Services.SAP.ZCCH_CACHE_PUTResponse1 ZCCH_CACHE_PUT(eContracting.Services.SAP.ZCCH_CACHE_PUTRequest request) {
            return base.Channel.ZCCH_CACHE_PUT(request);
        }
        
        public System.Threading.Tasks.Task<eContracting.Services.SAP.ZCCH_CACHE_PUTResponse1> ZCCH_CACHE_PUTAsync(eContracting.Services.SAP.ZCCH_CACHE_PUTRequest request) {
            return base.Channel.ZCCH_CACHE_PUTAsync(request);
        }
    }
}
