---
ID: "4bef4f2d-5d02-4e0b-ab6e-828c147f0d79"
Parent: "0c212fac-007e-4b30-a42e-44613d538683"
Template: "e269fbb5-3750-427a-9149-7aa950b49301"
Path: /sitecore/templates/eContracting/RenderingParameters/Modal window/MW01RenderingParameters/Parameters
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20181016T090040Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
