---
ID: "5f688b8c-1630-4c86-bf35-a5940c77f227"
Parent: "0a936432-a755-423d-8a8a-9d24dd0bcf72"
Template: "0a936432-a755-423d-8a8a-9d24dd0bcf72"
Path: /sitecore/templates/eContracting/Pages/eContractingThankYouTemplate/__Standard Values
DB: master
SharedFields:
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 300
- ID: "f1a1fe9e-a60c-4ddb-a3a0-bb5b29fe732e"
  Hint: __Renderings
  Type: layout
  Value: |
    <r xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <d
        id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}"
        l="{6BCF6E0C-75FE-4749-ACA3-9E8AA5B4B3C9}">
        <r
          ds=""
          id="{7B1673D7-C7B6-44D3-9BA4-4154E5D0D77A}"
          par=""
          ph="eContracting"
          uid="{6C0E87E7-35CF-44EB-8D70-81D852E106AB}" />
      </d>
    </r>
Languages:
- Language: cs
  Versions:
  - Version: 1
    Fields:
    - ID: "185ff4f7-54b0-4871-bbda-dfeb3d430a26"
      Hint: MainTextAcquisitionCampaign
      Value: MainTextAcquisitionCampaign
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200422T090319Z
    - ID: "4b5e53ef-28ed-4534-8239-7420d434d2da"
      Hint: MainTextRetentionCampaign
      Value: MainTextRetentionCampaign
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "a40b64bb-6a6b-434f-85ea-df6ac93ebc32"
      Hint: MainTextIndividual
      Value: MainTextIndividual
    - ID: "cb15dd47-a944-425e-998a-4a633ab36182"
      Hint: MainTextRetentionIndividual
      Value: MainTextRetentionIndividual
    - ID: "d0af4916-6383-4674-93d1-a489314a8f48"
      Hint: MainTextAcquisitionIndividual
      Value: MainTextAcquisitionIndividual
    - ID: "e78d0b43-4605-479e-b5c6-596cb0dc72be"
      Hint: MainTextCampaign
      Value: MainTextCampaign
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20161006T115617Z
