---
ID: "847cd829-2e85-4a6f-9ccb-85198db30c96"
Parent: "e4f4a320-3072-4e2d-a13c-eaee2fd09d5a"
Template: "e4f4a320-3072-4e2d-a13c-eaee2fd09d5a"
Path: /sitecore/templates/eContracting2/Pages/User Blocked/__Standard Values
DB: master
SharedFields:
- ID: "f1a1fe9e-a60c-4ddb-a3a0-bb5b29fe732e"
  Hint: __Renderings
  Type: layout
  Value: |
    <r xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <d
        id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}"
        l="{37DC70FC-BEB9-4179-9FCC-F2E35CC61BCA}">
        <r
          id="{1908A5F2-615A-4B62-8EA2-ABE628197FC2}"
          ph="eContracting2"
          uid="{C4CA234E-098C-49DF-965D-5CD0ED9894BF}" />
      </d>
    </r>
Languages:
- Language: cs
  Versions:
  - Version: 1
    Fields:
    - ID: "1554213a-29a2-4438-ac4b-589d951439a0"
      Hint: Header
      Value: Uživatel byl zablokován
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20201007T125245Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "a2b8abdd-d8aa-49f4-b3dd-27fea3f7da6e"
      Hint: PageTitle
      Value: Zablokovaný uživatel
    - ID: "cc065759-7f97-48ee-bcab-0f1a671b776d"
      Hint: MainText
      Value: |
        <p style="color: #000000;">V&aacute;žen&yacute; pane/pan&iacute;,</p>
        <p style="color: #000000;"> chybn&eacute; přihl&aacute;&scaron;en&iacute; způsobilo dočasn&eacute; zablokov&aacute;n&iacute; &uacute;čtu.</p>
        <p style="color: #000000;">Přihl&aacute;&scaron;en&iacute;  můžete zopakovat za 30 min, kdy dojde k odblokov&aacute;n&iacute; &uacute;čtu.</p>
        <p style="color: #000000;">Děkujeme</p>
        <p style="color: #000000;">Va&scaron;e innogy</p>
        <div>&nbsp;</div>
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20161006T115622Z
