---
ID: "bd9baf06-9f96-46c6-8163-dda6d43bed11"
Parent: "456d5421-a2de-42b4-97e6-a42fc243bf10"
Template: "456d5421-a2de-42b4-97e6-a42fc243bf10"
Path: /sitecore/templates/eContracting2/Pages/Offer/__Standard Values
DB: master
SharedFields:
- ID: "f1a1fe9e-a60c-4ddb-a3a0-bb5b29fe732e"
  Hint: __Renderings
  Type: layout
  Value: |
    <r xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <d
        id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}"
        l="{6BCF6E0C-75FE-4749-ACA3-9E8AA5B4B3C9}">
        <r
          ds=""
          id="{FB227820-1C8E-42E1-85BA-5D4F8C40F064}"
          par=""
          ph="eContracting"
          uid="{9ABFCF77-B688-44BA-9978-6012EEFFC595}" />
      </d>
    </r>
Languages:
- Language: cs
  Versions:
  - Version: 1
    Fields:
    - ID: "060d6406-b519-442f-9913-ec7118f6072b"
      Hint: MainTextRetentionCampaign
      Value: |
        <p>{CUSTTITLELET},</p>
        <p>ověřen&iacute; Va&scaron;ich &uacute;dajů proběhlo v poř&aacute;dku.</p>
        <p>N&iacute;že naleznete smluvn&iacute; dokumentaci k nab&iacute;zen&eacute;mu produktu.</p>
        <p>Nejdř&iacute;ve si, pros&iacute;m, přečtěte a zatrhněte Poučen&iacute;. Pot&eacute; se V&aacute;m zobraz&iacute; dal&scaron;&iacute; dokumenty, jejichž přečten&iacute; potvrďte takt&eacute;ž zatržen&iacute;m u každ&eacute;ho z nich.</p>
        <p>Stisknut&iacute;m tlač&iacute;tka Akceptuji potvrďte souhlas s uzavřen&iacute;m dodatku.</p>
    - ID: "1d0d678a-7393-43c8-b786-9220be7ec78f"
      Hint: MainTextAcquisitionCampaign
      Value: |
        <p>{CUSTTITLELET},</p>
        <p>ověřen&iacute; Va&scaron;ich &uacute;dajů proběhlo v poř&aacute;dku.</p>
        <p>N&iacute;že naleznete smluvn&iacute; dokumentaci k nab&iacute;zen&eacute;mu produktu.</p>
        <p>Nejdř&iacute;ve si, pros&iacute;m, přečtěte a zatrhněte Poučen&iacute;. Pot&eacute; se V&aacute;m zobraz&iacute; dal&scaron;&iacute; dokumenty, jejichž přečten&iacute; potvrďte takt&eacute;ž zatržen&iacute;m u každ&eacute;ho z nich.</p>
        <p>Stisknut&iacute;m tlač&iacute;tka Akceptuji potvrďte souhlas s uzavřen&iacute;m dodatku.</p>
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200421T112121Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "63b4f770-3576-4dd2-9007-ece3c1d0b2ce"
      Hint: VoucherText
      Value: "Podpisem smlouvy z&iacute;sk&aacute;te {GIFT_NOW_NAME}."
    - ID: "7c3c09e7-21cc-4812-8ce2-d8a1dd500872"
      Hint: MainTextCampaign
      Value: |
        <p>{CUSTTITLELET},</p>
        <p>ověřen&iacute; Va&scaron;ich &uacute;dajů proběhlo v poř&aacute;dku.</p>
        <p>N&iacute;že naleznete smluvn&iacute; dokumentaci k nab&iacute;zen&eacute;mu produktu.</p>
        <p>Nejdř&iacute;ve si, pros&iacute;m, přečtěte a zatrhněte Poučen&iacute;. Pot&eacute; se V&aacute;m zobraz&iacute; dal&scaron;&iacute; dokumenty, jejichž přečten&iacute; potvrďte takt&eacute;ž zatržen&iacute;m u každ&eacute;ho z nich.</p>
        <p>Stisknut&iacute;m tlač&iacute;tka Akceptuji potvrďte souhlas s uzavřen&iacute;m dodatku.</p>
    - ID: "a44a73c3-ad9d-4e6d-833e-ce4e6512c61d"
      Hint: AcquistionVoucherText
      Value: "Podpisem smlouvy z&iacute;sk&aacute;te {GIFT_NOW_NAME}."
    - ID: "b9653e38-ac49-41f8-af0b-05153843f6ac"
      Hint: MainTextIndividual
      Value: |
        <p>{CUSTTITLELET},</p>
        <p>ověřen&iacute; Va&scaron;ich &uacute;dajů proběhlo v poř&aacute;dku.</p>
        <p>N&iacute;že naleznete smluvn&iacute; dokumentaci k nab&iacute;zen&eacute;mu produktu.</p>
        <p>Nejdř&iacute;ve si, pros&iacute;m, přečtěte a zatrhněte Poučen&iacute;. Pot&eacute; se V&aacute;m zobraz&iacute; dal&scaron;&iacute; dokumenty, jejichž přečten&iacute; potvrďte takt&eacute;ž zatržen&iacute;m u každ&eacute;ho z nich.</p>
        <p>Stisknut&iacute;m tlač&iacute;tka Akceptuji potvrďte souhlas s uzavřen&iacute;m dodatku.</p>
    - ID: "c18260e9-e843-4a82-9e17-ab59cdb29c1c"
      Hint: RetentionVoucherText
      Value: "Podpisem smlouvy z&iacute;sk&aacute;te {GIFT_NOW_NAME}."
    - ID: "d38e0859-6b63-4d48-b042-0d5d895dda51"
      Hint: MainTextRetentionIndividual
      Value: |
        <p>{CUSTTITLELET},</p>
        <p>ověřen&iacute; Va&scaron;ich &uacute;dajů proběhlo v poř&aacute;dku.</p>
        <p>N&iacute;že naleznete smluvn&iacute; dokumentaci k nab&iacute;zen&eacute;mu produktu.</p>
        <p>Nejdř&iacute;ve si, pros&iacute;m, přečtěte a zatrhněte Poučen&iacute;. Pot&eacute; se V&aacute;m zobraz&iacute; dal&scaron;&iacute; dokumenty, jejichž přečten&iacute; potvrďte takt&eacute;ž zatržen&iacute;m u každ&eacute;ho z nich.</p>
        <p>Stisknut&iacute;m tlač&iacute;tka Akceptuji potvrďte souhlas s uzavřen&iacute;m dodatku.</p>
    - ID: "e939843c-4e9f-437f-b4be-c1d57f00bbaa"
      Hint: MainTextAcquisitionIndividual
      Value: |
        <p>{CUSTTITLELET},</p>
        <p>ověřen&iacute; Va&scaron;ich &uacute;dajů proběhlo v poř&aacute;dku.</p>
        <p>N&iacute;že naleznete smluvn&iacute; dokumentaci k nab&iacute;zen&eacute;mu produktu.</p>
        <p>Nejdř&iacute;ve si, pros&iacute;m, přečtěte a zatrhněte Poučen&iacute;. Pot&eacute; se V&aacute;m zobraz&iacute; dal&scaron;&iacute; dokumenty, jejichž přečten&iacute; potvrďte takt&eacute;ž zatržen&iacute;m u každ&eacute;ho z nich.</p>
        <p>Stisknut&iacute;m tlač&iacute;tka Akceptuji potvrďte souhlas s uzavřen&iacute;m dodatku.</p>
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20161006T115550Z
