//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eContracting.SignStamp {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:sap-com:sprx:ep:cust:Z", ConfigurationName="SignStamp.CRM_SIGN_STAMP_MERGE")]
    public interface CRM_SIGN_STAMP_MERGE {
        
        // CODEGEN: Generating message contract since the operation invoke is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="urn:sap-com:sprx:ep:cust:Z:CRM_SIGN_STAMP_MERGE:invokeRequest", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        eContracting.SignStamp.invokeResponse1 invoke(eContracting.SignStamp.invokeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:sap-com:sprx:ep:cust:Z:CRM_SIGN_STAMP_MERGE:invokeRequest", ReplyAction="*")]
        System.Threading.Tasks.Task<eContracting.SignStamp.invokeResponse1> invokeAsync(eContracting.SignStamp.invokeRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://adobe.com/idp/services")]
    public partial class invoke : object, System.ComponentModel.INotifyPropertyChanged {
        
        private BLOB inputPDFField;
        
        private BLOB inputPNGSignField;
        
        private string overlayField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public BLOB inputPDF {
            get {
                return this.inputPDFField;
            }
            set {
                this.inputPDFField = value;
                this.RaisePropertyChanged("inputPDF");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public BLOB inputPNGSign {
            get {
                return this.inputPNGSignField;
            }
            set {
                this.inputPNGSignField = value;
                this.RaisePropertyChanged("inputPNGSign");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string overlay {
            get {
                return this.overlayField;
            }
            set {
                this.overlayField = value;
                this.RaisePropertyChanged("overlay");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://adobe.com/idp/services")]
    public partial class BLOB : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string contentTypeField;
        
        private byte[] binaryDataField;
        
        private string attachmentIDField;
        
        private string remoteURLField;
        
        private byte[] mTOMField;
        
        private string swaRefField;
        
        private MyMapOf_xsd_string_To_xsd_anyType_Item[] attributesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string contentType {
            get {
                return this.contentTypeField;
            }
            set {
                this.contentTypeField = value;
                this.RaisePropertyChanged("contentType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=1)]
        public byte[] binaryData {
            get {
                return this.binaryDataField;
            }
            set {
                this.binaryDataField = value;
                this.RaisePropertyChanged("binaryData");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string attachmentID {
            get {
                return this.attachmentIDField;
            }
            set {
                this.attachmentIDField = value;
                this.RaisePropertyChanged("attachmentID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string remoteURL {
            get {
                return this.remoteURLField;
            }
            set {
                this.remoteURLField = value;
                this.RaisePropertyChanged("remoteURL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=4)]
        public byte[] MTOM {
            get {
                return this.mTOMField;
            }
            set {
                this.mTOMField = value;
                this.RaisePropertyChanged("MTOM");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI", Order=5)]
        public string swaRef {
            get {
                return this.swaRefField;
            }
            set {
                this.swaRefField = value;
                this.RaisePropertyChanged("swaRef");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=6)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", IsNullable=false)]
        public MyMapOf_xsd_string_To_xsd_anyType_Item[] attributes {
            get {
                return this.attributesField;
            }
            set {
                this.attributesField = value;
                this.RaisePropertyChanged("attributes");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://adobe.com/idp/services")]
    public partial class MyMapOf_xsd_string_To_xsd_anyType_Item : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string keyField;
        
        private object valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
                this.RaisePropertyChanged("key");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public object value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://adobe.com/idp/services")]
    public partial class invokeResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int errCodeField;
        
        private string errMsgField;
        
        private BLOB outputPDFField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int errCode {
            get {
                return this.errCodeField;
            }
            set {
                this.errCodeField = value;
                this.RaisePropertyChanged("errCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string errMsg {
            get {
                return this.errMsgField;
            }
            set {
                this.errMsgField = value;
                this.RaisePropertyChanged("errMsg");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public BLOB outputPDF {
            get {
                return this.outputPDFField;
            }
            set {
                this.outputPDFField = value;
                this.RaisePropertyChanged("outputPDF");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class invokeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://adobe.com/idp/services", Order=0)]
        public eContracting.SignStamp.invoke invoke;
        
        public invokeRequest() {
        }
        
        public invokeRequest(eContracting.SignStamp.invoke invoke) {
            this.invoke = invoke;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class invokeResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://adobe.com/idp/services", Order=0)]
        public eContracting.SignStamp.invokeResponse invokeResponse;
        
        public invokeResponse1() {
        }
        
        public invokeResponse1(eContracting.SignStamp.invokeResponse invokeResponse) {
            this.invokeResponse = invokeResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CRM_SIGN_STAMP_MERGEChannel : eContracting.SignStamp.CRM_SIGN_STAMP_MERGE, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CRM_SIGN_STAMP_MERGEClient : System.ServiceModel.ClientBase<eContracting.SignStamp.CRM_SIGN_STAMP_MERGE>, eContracting.SignStamp.CRM_SIGN_STAMP_MERGE {
        
        public CRM_SIGN_STAMP_MERGEClient() {
        }
        
        public CRM_SIGN_STAMP_MERGEClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CRM_SIGN_STAMP_MERGEClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CRM_SIGN_STAMP_MERGEClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CRM_SIGN_STAMP_MERGEClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        eContracting.SignStamp.invokeResponse1 eContracting.SignStamp.CRM_SIGN_STAMP_MERGE.invoke(eContracting.SignStamp.invokeRequest request) {
            return base.Channel.invoke(request);
        }
        
        public eContracting.SignStamp.invokeResponse invoke(eContracting.SignStamp.invoke invoke1) {
            eContracting.SignStamp.invokeRequest inValue = new eContracting.SignStamp.invokeRequest();
            inValue.invoke = invoke1;
            eContracting.SignStamp.invokeResponse1 retVal = ((eContracting.SignStamp.CRM_SIGN_STAMP_MERGE)(this)).invoke(inValue);
            return retVal.invokeResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<eContracting.SignStamp.invokeResponse1> eContracting.SignStamp.CRM_SIGN_STAMP_MERGE.invokeAsync(eContracting.SignStamp.invokeRequest request) {
            return base.Channel.invokeAsync(request);
        }
        
        public System.Threading.Tasks.Task<eContracting.SignStamp.invokeResponse1> invokeAsync(eContracting.SignStamp.invoke invoke) {
            eContracting.SignStamp.invokeRequest inValue = new eContracting.SignStamp.invokeRequest();
            inValue.invoke = invoke;
            return ((eContracting.SignStamp.CRM_SIGN_STAMP_MERGE)(this)).invokeAsync(inValue);
        }
    }
}
