---
ID: "1b7a52a4-82f2-49ff-bd51-733f19b87ca0"
Parent: "c8c58d58-c5d9-47c2-aef3-f4defca62a2c"
Template: "c8c58d58-c5d9-47c2-aef3-f4defca62a2c"
Path: /sitecore/templates/eContracting2/Pages/Login/__Standard Values
DB: master
SharedFields:
- ID: "344ba390-9f68-4c6e-bdde-4debd7fe9dad"
  Hint: AutoGenerateTestableCombinationPlaceholders
  Type: Checkbox
  Value: 1
- ID: "a4f985d9-98b3-4b52-aaaf-4344f6e747c6"
  Hint: __Workflow
  Value: 
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 387
- ID: "f1a1fe9e-a60c-4ddb-a3a0-bb5b29fe732e"
  Hint: __Renderings
  Type: layout
  Value: |
    <r xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <d
        id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}"
        l="{37DC70FC-BEB9-4179-9FCC-F2E35CC61BCA}">
        <r
          id="{C9E6964D-A594-4A57-A933-8DBEAE72A896}"
          ph="eContracting2Top"
          uid="{E0DE4DAD-AF0D-4CF0-AA70-964E82CC5657}" />
        <r
          ds="{FEDC5ECD-CB1B-46FE-838A-859C9BF683FD}"
          id="{C6B149DB-135E-4A89-B58F-91E6544C10D0}"
          par=""
          ph="eContracting2Top"
          uid="{0B8EA37E-00C7-47C9-9562-C070E573E9A0}" />
        <r
          id="{994F14EA-C859-4055-BB0E-523CE476057A}"
          ph="/eContracting2Main/eContracting2-login"
          uid="{F6C9BA92-0929-444F-BE87-E9DF1B4ADA32}" />
        <r
          ds="{1EBB80D7-AE0C-4A0C-8CD4-6EFC5F4148C6}"
          id="{C2060F07-1E5B-4679-82D9-0114EAC77CF3}"
          par=""
          ph="eContracting2Bottom"
          uid="{1F951A91-EBBA-4F44-8AC8-7319772D5BB2}" />
      </d>
    </r>
Languages:
- Language: cs
  Versions:
  - Version: 1
    Fields:
    - ID: "03047546-9d8d-44e8-9f51-623bb86cfd24"
      Hint: VerificationMethodLabel
      Value: Vyberte způsob ověření
    - ID: "04bf00db-f5fb-41f7-8ab7-22408372a981"
      Hint: __Final Renderings
      Type: Layout
      Value: |
        <r xmlns:p="p" xmlns:s="s"
          p:p="1">
          <d
            id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}">
            <r
              uid="{CBD4DC5B-2DBF-4475-A67A-C2201C7B1E4B}"
              p:after="r[@uid='{0B8EA37E-00C7-47C9-9562-C070E573E9A0}']"
              s:ds=""
              s:id="{98B94438-C0B0-44A3-A32C-9078E992D049}"
              s:par=""
              s:ph="eContracting2Main" />
            <r
              uid="{1F951A91-EBBA-4F44-8AC8-7319772D5BB2}"
              p:after="*[1=2]" />
          </d>
        </r>
    - ID: "088b75ed-cffd-46df-8f94-6a19de7cb292"
      Hint: BirthDateLabel
      Value: Datum narození
    - ID: "09e5f8e2-f7b8-4a74-ad09-a16fc95123cc"
      Hint: ValidationMessage
      Value: Ověřen&iacute; Va&scaron;ich &uacute;dajů se nezdařilo. Zadejte, pros&iacute;m, spr&aacute;vn&eacute; &uacute;daje. V př&iacute;padě pot&iacute;ž&iacute; se, pros&iacute;m, obraťte na na&scaron;i z&aacute;kaznickou linku 800 11 33 55.
    - ID: "151df2b3-8e47-4a63-8f2a-5b166c8226ac"
      Hint: CampaignLabel
      Value: KAMPAN
    - ID: "17eccf1c-7206-4211-a367-309c2c3f09c6"
      Hint: CalendarSelectDay
      Value: Vybrat
    - ID: "1e1ac363-df62-478b-9e0f-9567b429d6ae"
      Hint: WarningDontHaveAccess
      Value: |
        <p style="text-align: center;"><strong><span>Je n&aacute;m l&iacute;to, ale V&aacute;&scaron; aktu&aacute;lně přihl&aacute;&scaron;en&yacute; innogy &uacute;čet nem&aacute; př&iacute;stup k dan&eacute; nab&iacute;dce. Pros&iacute;m, použijte tuto možnost ověřen&iacute;.</span></strong></p>
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200818T094403Z
    - ID: "26908a98-0ab1-47bd-a38a-db6b282dd9c5"
      Hint: BirthDatePlaceholder
      Value: např. 26. 12. 1966
    - ID: "2f6761a0-295f-48fd-95f8-7a3aa75fd93a"
      Hint: IndividualLabel
      Value: INDI
    - ID: "31a8a6a1-820d-44c9-842d-6052c4fdc69e"
      Hint: CalendarOpen
      Value: Otevřít kalendář
    - ID: "35e1dac4-5051-4200-a3f2-d33b4dd43095"
      Hint: RequiredFields
      Value: Vyplňte pros&iacute;m v&scaron;echna požadovan&aacute; pole.
    - ID: "39dd7778-79b9-48bc-9318-c22bd3e09595"
      Hint: LoginView_eCat
      Value: Runway
    - ID: "417e461e-a119-4cee-84d9-5d6193337e33"
      Hint: LoginClick_eCat
      Value: Runway
    - ID: "450560cf-4b56-4824-8df0-e6041ec6f072"
      Hint: BirthDateValidationMessage
      Value: Zadáno chybné datum narození.
    - ID: "4c6a3388-f488-4e84-83e6-71184cd7cf8c"
      Hint: CalendarNextMonth
      Value: Další měsíc
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "6305a328-3ac5-4e35-b716-94ddc3a26340"
      Hint: ButtonText
      Value: Potvrdit údaje a zobrazit nabídku
    - ID: "679e4219-6b12-4070-a067-86a6cd60079c"
      Hint: LoginView_eAct
      Value: "Zobrazeni-eCon-login"
    - ID: "7a86ecaf-d3a9-4116-aaa3-4e9b50b21f73"
      Hint: ElectricityLabel
      Value: elektrina
    - ID: "7fd9b68e-9184-4334-b147-854889749672"
      Hint: LoginView_eLab
      Value: "{TYPE}_Start_15-{BUS_PROCESS}"
    - ID: "a2b8abdd-d8aa-49f4-b3dd-27fea3f7da6e"
      Hint: PageTitle
      Value: Ověření totožnosti
    - ID: "aa080911-981e-4a37-b765-cefff6c6d30d"
      Hint: LoginClick_eLab
      Value: "{TYPE}_Start_15-{BUS_PROCESS}"
    - ID: "b52ff037-5b18-4a5a-ab6f-ef4852af9646"
      Hint: GasLabel
      Value: plyn
    - ID: "d0347707-54d7-4e06-8d3a-afac3c8b4af3"
      Hint: BirthDateHelpMessage
      Value: |
        Datum narození můžete zadat ve formátu:<br />
        D.M.RRRR<br />
        D.MM.RRRR<br />
        DD.M.RRRR<br />
        DD.MM.RRRR
        
    - ID: "e973d772-5286-40ec-b678-2c13dea139e9"
      Hint: CalendarPreviousMonth
      Value: Předchozí měsíc
    - ID: "eb6c2fc3-7f83-4798-afff-f9b5e5dc1402"
      Hint: LoginClick_eAct
      Value: "Proklik-eCon-login"
