---
ID: "a3be5498-0c77-49b1-a59d-a87d3135fd38"
Parent: "89052c3a-8d1d-427e-9f4c-24fb58de21ce"
Template: "89052c3a-8d1d-427e-9f4c-24fb58de21ce"
Path: /sitecore/templates/eContracting/Pages/eContractingOfferTemplate/__Standard Values
DB: master
SharedFields:
- ID: "f1a1fe9e-a60c-4ddb-a3a0-bb5b29fe732e"
  Hint: __Renderings
  Type: layout
  Value: |
    <r xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <d
        id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}"
        l="{6BCF6E0C-75FE-4749-ACA3-9E8AA5B4B3C9}">
        <r
          ds=""
          id="{FB227820-1C8E-42E1-85BA-5D4F8C40F064}"
          par=""
          ph="eContracting"
          uid="{9ABFCF77-B688-44BA-9978-6012EEFFC595}" />
      </d>
    </r>
Languages:
- Language: cs
  Versions:
  - Version: 1
    Fields:
    - ID: "119129bb-7396-463a-a225-8f1cc0c7e706"
      Hint: MainTextCampaign
      Value: |
        <p>{CUSTTITLELET},</p>
        <p>ověřen&iacute; Va&scaron;ich &uacute;dajů proběhlo v poř&aacute;dku.</p>
        <p>N&iacute;že naleznete smluvn&iacute; dokumentaci k nab&iacute;zen&eacute;mu produktu.</p>
        <p>Nejdř&iacute;ve si, pros&iacute;m, přečtěte a zatrhněte Poučen&iacute;. Pot&eacute; se V&aacute;m zobraz&iacute; dal&scaron;&iacute; dokumenty, jejichž přečten&iacute; potvrďte takt&eacute;ž zatržen&iacute;m u každ&eacute;ho z nich.</p>
        <p>Stisknut&iacute;m tlač&iacute;tka Akceptuji potvrďte souhlas s uzavřen&iacute;m dodatku.</p>
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200421T112121Z
    - ID: "30a610c9-4449-4187-8626-733445fe4bf3"
      Hint: MainTextRetentionCampaign
      Value: |
        <p>{CUSTTITLELET},</p>
        <p>ověřen&iacute; Va&scaron;ich &uacute;dajů proběhlo v poř&aacute;dku.</p>
        <p>N&iacute;že naleznete smluvn&iacute; dokumentaci k nab&iacute;zen&eacute;mu produktu.</p>
        <p>Nejdř&iacute;ve si, pros&iacute;m, přečtěte a zatrhněte Poučen&iacute;. Pot&eacute; se V&aacute;m zobraz&iacute; dal&scaron;&iacute; dokumenty, jejichž přečten&iacute; potvrďte takt&eacute;ž zatržen&iacute;m u každ&eacute;ho z nich.</p>
        <p>Stisknut&iacute;m tlač&iacute;tka Akceptuji potvrďte souhlas s uzavřen&iacute;m dodatku.</p>
    - ID: "3927d924-70fc-46e1-9b8a-76c9bbb67499"
      Hint: MainTextRetentionIndividual
      Value: |
        <p>{CUSTTITLELET},</p>
        <p>ověřen&iacute; Va&scaron;ich &uacute;dajů proběhlo v poř&aacute;dku.</p>
        <p>N&iacute;že naleznete smluvn&iacute; dokumentaci k nab&iacute;zen&eacute;mu produktu.</p>
        <p>Nejdř&iacute;ve si, pros&iacute;m, přečtěte a zatrhněte Poučen&iacute;. Pot&eacute; se V&aacute;m zobraz&iacute; dal&scaron;&iacute; dokumenty, jejichž přečten&iacute; potvrďte takt&eacute;ž zatržen&iacute;m u každ&eacute;ho z nich.</p>
        <p>Stisknut&iacute;m tlač&iacute;tka Akceptuji potvrďte souhlas s uzavřen&iacute;m dodatku.</p>
    - ID: "56b78aee-8090-44fe-ae96-7c2384373fb5"
      Hint: MainTextAcquisitionIndividual
      Value: |
        <p>{CUSTTITLELET},</p>
        <p>ověřen&iacute; Va&scaron;ich &uacute;dajů proběhlo v poř&aacute;dku.</p>
        <p>N&iacute;že naleznete smluvn&iacute; dokumentaci k nab&iacute;zen&eacute;mu produktu.</p>
        <p>Nejdř&iacute;ve si, pros&iacute;m, přečtěte a zatrhněte Poučen&iacute;. Pot&eacute; se V&aacute;m zobraz&iacute; dal&scaron;&iacute; dokumenty, jejichž přečten&iacute; potvrďte takt&eacute;ž zatržen&iacute;m u každ&eacute;ho z nich.</p>
        <p>Stisknut&iacute;m tlač&iacute;tka Akceptuji potvrďte souhlas s uzavřen&iacute;m dodatku.</p>
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "76412c60-08a3-40d7-b92c-ee387988203c"
      Hint: MainTextIndividual
      Value: |
        <p>{CUSTTITLELET},</p>
        <p>ověřen&iacute; Va&scaron;ich &uacute;dajů proběhlo v poř&aacute;dku.</p>
        <p>N&iacute;že naleznete smluvn&iacute; dokumentaci k nab&iacute;zen&eacute;mu produktu.</p>
        <p>Nejdř&iacute;ve si, pros&iacute;m, přečtěte a zatrhněte Poučen&iacute;. Pot&eacute; se V&aacute;m zobraz&iacute; dal&scaron;&iacute; dokumenty, jejichž přečten&iacute; potvrďte takt&eacute;ž zatržen&iacute;m u každ&eacute;ho z nich.</p>
        <p>Stisknut&iacute;m tlač&iacute;tka Akceptuji potvrďte souhlas s uzavřen&iacute;m dodatku.</p>
    - ID: "b0c226b0-448e-45bd-8eed-432ddf9fdf66"
      Hint: MainTextAcquisitionCampaign
      Value: |
        <p>{CUSTTITLELET},</p>
        <p>ověřen&iacute; Va&scaron;ich &uacute;dajů proběhlo v poř&aacute;dku.</p>
        <p>N&iacute;že naleznete smluvn&iacute; dokumentaci k nab&iacute;zen&eacute;mu produktu.</p>
        <p>Nejdř&iacute;ve si, pros&iacute;m, přečtěte a zatrhněte Poučen&iacute;. Pot&eacute; se V&aacute;m zobraz&iacute; dal&scaron;&iacute; dokumenty, jejichž přečten&iacute; potvrďte takt&eacute;ž zatržen&iacute;m u každ&eacute;ho z nich.</p>
        <p>Stisknut&iacute;m tlač&iacute;tka Akceptuji potvrďte souhlas s uzavřen&iacute;m dodatku.</p>
    - ID: "b76c43cc-24da-4f8c-95f1-6099dece51c8"
      Hint: AcquistionVoucherText
      Value: "Podpisem smlouvy z&iacute;sk&aacute;te {GIFT_NOW_NAME}."
    - ID: "bee64f75-a4ca-44cb-8d56-d60108c60303"
      Hint: VoucherText
      Value: "Podpisem smlouvy z&iacute;sk&aacute;te {GIFT_NOW_NAME}."
    - ID: "d4c4044a-c31d-4ae9-bf7c-100b9019d35d"
      Hint: RetentionVoucherText
      Value: "Podpisem smlouvy z&iacute;sk&aacute;te {GIFT_NOW_NAME}."
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20161006T115550Z
