---
ID: "6863430f-ecb4-4d68-bdb7-d06ee85df2ca"
Parent: "37a0c216-ff0f-461c-81f3-c3478c3cc6a2"
Template: "455a3e98-a627-4b40-8035-e683a0331ac7"
Path: /sitecore/templates/eContracting2/WebRoot/1 General/ApplicationUnavailableTitle
DB: master
SharedFields:
- ID: "ab162cc0-dc80-4abf-8871-998ee5d7ba32"
  Hint: Type
  Value: "Single-Line Text"
- ID: "b118496a-0f78-4a27-b55f-0a6c4b0b0fe1"
  Hint: Default value
  Value: Nedostupnost aplikace
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 100
Languages:
- Language: cs
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20201120T140823Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
- Language: en
  Fields:
  - ID: "19a69332-a23e-4e70-8d16-b2640cb24cc8"
    Hint: Title
    Value: "Nedostupnost aplikace - nadpis"
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20201123T113346Z
