---
ID: "ef46ecee-a9f6-4b2e-81e3-e790601a68bb"
Parent: "0eeae94d-0018-40c8-a537-5b67349985cd"
Template: "0eeae94d-0018-40c8-a537-5b67349985cd"
Path: /sitecore/templates/eContracting/Pages/eContractingAuthenticationTemplate/__Standard Values
DB: master
SharedFields:
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 500
- ID: "f1a1fe9e-a60c-4ddb-a3a0-bb5b29fe732e"
  Hint: __Renderings
  Type: layout
  Value: |
    <r xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <d
        id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}"
        l="{772D75F9-CE2A-4D4C-B452-533FC32E9329}">
        <r
          ds=""
          id="{E3A237FE-78F5-449E-BEFA-02BFC5C5FE55}"
          par=""
          ph="eContracting"
          uid="{25E56EA6-4C83-41CA-B8A8-5B084A0A7195}" />
      </d>
    </r>
Languages:
- Language: cs
  Versions:
  - Version: 1
    Fields:
    - ID: "06c254b3-1987-426e-97fe-29639387ef2d"
      Hint: ZipCodeLabel
      Value: PSČ trvalého bydliště
    - ID: "07c8ef11-d295-43e1-b44f-905394013a45"
      Hint: CustomerNumberPlaceholder
      Value: 123456789
    - ID: "1d0e9733-e58e-424b-bcf8-bf4ce86e60a4"
      Hint: CalendarNextMonth
      Value: Další měsíc
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200818T094403Z
    - ID: "4cf2ae09-7e92-441e-9f6b-d448b83cf1b7"
      Hint: VerificationMethod
      Value: Vyberte způsob ověření
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "5ff04122-3235-4975-9721-88a2987944c8"
      Hint: CalendarSelectDay
      Value: Vybrat
    - ID: "8a112f96-eb98-43ad-a6e5-e63c035a43fa"
      Hint: ButtonText
      Value: Potvrdit údaje a zobrazit nabídku
    - ID: "91f9d7b6-b0b8-40c2-88fd-d5ada146ac4d"
      Hint: BirthDatePlaceholder
      Value: např. 26. 12. 1966
    - ID: "930b11f4-0669-48cd-9168-ae41831375f0"
      Hint: CustomerNumberLabel
      Value: Zákaznické číslo
    - ID: "a3b73ecd-34cc-47eb-8a77-7e5173e7e1f0"
      Hint: CustomerNumberHelpText
      Value: Jedná se o číslo uvedené na Vaší smlouvě
    - ID: "c5bc29d2-43b0-41f0-a2f5-0116d87af26a"
      Hint: BirthDateLabel
      Value: Datum narození
    - ID: "dbeadb02-72dc-4cea-b973-957d422a0a29"
      Hint: ZipCodeHelpText
      Value: Vyplňte pouze čísla
    - ID: "e101cb3d-80e5-48fc-bad3-9863506454e6"
      Hint: ZipCodePlaceholder
      Value: 15500
    - ID: "e6764717-513e-480b-b317-d23cb8d3b97e"
      Hint: CalendarPreviousMonth
      Value: Předchozí měsíc
    - ID: "ec7fbaab-d4b7-4265-8924-14e83054141f"
      Hint: CalendarOpen
      Value: Otevřít kalendář
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20161006T115526Z
    - ID: "998c5baf-5b8c-417e-918b-14e1b330ff06"
      Hint: ContractSecondPropertyLabel
      Value: Vyberte si druhý smluvní údaj pro přihlášení
