---
ID: "b5e5e29b-9384-4864-a163-b32c0a8d910f"
Parent: "6d22f9b3-29ff-4568-8896-5b3cf78569a4"
Template: "6d22f9b3-29ff-4568-8896-5b3cf78569a4"
Path: /sitecore/templates/eContracting2/Datasources/Steps/__Standard Values
DB: master
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Type: TreelistEx
  Value: "{7691585A-BB36-4EE7-937F-DA4DE7A3EDEC}"
Languages:
- Language: cs
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20201007T150011Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
