---
ID: "fe8034fd-3fdf-455c-939b-75d2e017c55d"
Parent: "35e8b33e-a44d-4e2a-a5d0-7becb710b8f1"
Template: "35e8b33e-a44d-4e2a-a5d0-7becb710b8f1"
Path: /sitecore/templates/eContracting/Resources/ThankYouPageSettings/__Standard Values
DB: master
Languages:
- Language: cs
  Versions:
  - Version: 1
    Fields:
    - ID: "089f7945-5aaa-455f-a6ad-d8b3b3e99c65"
      Hint: eLabText
      Value: "{0} - {1}"
    - ID: "1b8fa8fe-d388-4e59-b634-c80eb0a932a0"
      Hint: GasLabel
      Value: ZP
    - ID: "2533c7fb-abad-48a3-b4ea-f59de0fb6f28"
      Hint: ElectricityLabel
      Value: EE
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200420T092316Z
    - ID: "476f6d29-3163-43f5-af6f-22b3c73a9823"
      Hint: eCatText
      Value: "eCon {0} - Akceptace nabidky"
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "a2ced66d-f4c7-4810-b42c-6da2c3774f14"
      Hint: eActText
      Value: "eCon {0} - {1}"
    - ID: "bbc7a2e4-4aba-40b7-a29a-18e680cd90b6"
      Hint: IndividualLabel
      Value: INDI
    - ID: "d1141532-55e3-4820-af78-6d2373672fef"
      Hint: CampaignLabel
      Value: KAMPAN
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "089f7945-5aaa-455f-a6ad-d8b3b3e99c65"
      Hint: eLabText
      Value: "{0} - {1}"
    - ID: "1b8fa8fe-d388-4e59-b634-c80eb0a932a0"
      Hint: GasLabel
      Value: ZP
    - ID: "2533c7fb-abad-48a3-b4ea-f59de0fb6f28"
      Hint: ElectricityLabel
      Value: EE
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200417T080109Z
    - ID: "476f6d29-3163-43f5-af6f-22b3c73a9823"
      Hint: eCatText
      Value: "eCon {0} - Akceptace nabidky"
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "a2ced66d-f4c7-4810-b42c-6da2c3774f14"
      Hint: eActText
      Value: "eCon {0} - {1}"
    - ID: "bbc7a2e4-4aba-40b7-a29a-18e680cd90b6"
      Hint: IndividualLabel
      Value: INDI
    - ID: "d1141532-55e3-4820-af78-6d2373672fef"
      Hint: CampaignLabel
      Value: KAMPAN
