---
ID: "bf89cb49-0552-445b-887b-175073bd2a83"
Parent: "d7dac647-20e4-4c18-b578-927093bb0d39"
Template: "d7dac647-20e4-4c18-b578-927093bb0d39"
Path: /sitecore/templates/eContracting2/Pages/_Base/__Standard Values
DB: master
SharedFields:
- ID: "f1a1fe9e-a60c-4ddb-a3a0-bb5b29fe732e"
  Hint: __Renderings
  Type: layout
  Value: |
    <r xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <d
        id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}"
        l="{6BCF6E0C-75FE-4749-ACA3-9E8AA5B4B3C9}" />
    </r>
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20160907T095112Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
