---
ID: "3930704b-3708-4f82-b53c-49713731d3bb"
Parent: "0f225e4f-aa1e-44cc-91f4-19d4fb5c859c"
Template: "0f225e4f-aa1e-44cc-91f4-19d4fb5c859c"
Path: /sitecore/templates/eContracting2/Pages/Offer Accepted/__Standard Values
DB: master
SharedFields:
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 300
Languages:
- Language: cs
  Versions:
  - Version: 1
    Fields:
    - ID: "04bf00db-f5fb-41f7-8ab7-22408372a981"
      Hint: __Final Renderings
      Type: Layout
      Value: |
        <r xmlns:p="p" xmlns:s="s"
          p:p="1">
          <d
            id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}">
            <r
              uid="{C3CA92BE-7FC0-4D08-927F-483C51EB49FD}"
              p:after="r[@uid='{0B8EA37E-00C7-47C9-9562-C070E573E9A0}']"
              s:id="{6A924B55-716B-4026-8707-B641E7E42719}"
              s:ph="eContracting2Main" />
            <r
              uid="{1F951A91-EBBA-4F44-8AC8-7319772D5BB2}"
              p:after="*[1=2]" />
          </d>
        </r>
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200422T090019Z
    - ID: "3bb4d3cb-fed7-42e1-a067-f41f0e5f2b9b"
      Hint: ButtonDashboardLabel
      Value: Zobrazit přehled
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "a2b8abdd-d8aa-49f4-b3dd-27fea3f7da6e"
      Hint: PageTitle
      Value: Akceptovaná nabídka
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20161006T115522Z
