---
ID: "bd9baf06-9f96-46c6-8163-dda6d43bed11"
Parent: "456d5421-a2de-42b4-97e6-a42fc243bf10"
Template: "456d5421-a2de-42b4-97e6-a42fc243bf10"
Path: /sitecore/templates/eContracting2/Pages/Offer/__Standard Values
DB: master
SharedFields:
- ID: "a4f985d9-98b3-4b52-aaaf-4344f6e747c6"
  Hint: __Workflow
  Value: 
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 600
Languages:
- Language: cs
  Versions:
  - Version: 1
    Fields:
    - ID: "04bf00db-f5fb-41f7-8ab7-22408372a981"
      Hint: __Final Renderings
      Type: Layout
      Value: |
        <r xmlns:p="p" xmlns:s="s"
          p:p="1">
          <d
            id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}">
            <r
              uid="{DA612AA0-6397-4414-84DA-490EC7F5B3AC}"
              p:after="r[@uid='{0B8EA37E-00C7-47C9-9562-C070E573E9A0}']"
              s:id="{073F2938-DC30-44AD-9F46-B83A31D75652}"
              s:ph="eContracting2Main" />
            <r
              uid="{1F951A91-EBBA-4F44-8AC8-7319772D5BB2}"
              p:after="*[1=2]" />
          </d>
        </r>
    - ID: "0dcae80e-05f3-4a1b-92f2-dd14251e2cb1"
      Hint: GDPRUrl
      Value: "https://test-optin.innogy.cz/auth"
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200421T112121Z
    - ID: "4542333b-3ec7-4e59-aa7d-a8b62d2ba2e5"
      Hint: AesEncryptVector
      Value: l0W0jlqCwVQrWLSa
    - ID: "59fa2d18-799f-482d-88e3-c37a37e76444"
      Hint: AesEncryptKey
      Value: oEdvEcn24ofUe3gjXpFHYCd22ygalbXw
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "5f47da54-a894-47cd-b382-f9fca25ffba0"
      Hint: BackToSummaryLinkLabel
      Value: Zpět na nabídku
    - ID: "8d060b74-635e-4fe1-83e1-84b3c2f279d5"
      Hint: StartAgainLinkLabel
      Value: Začít znovu
    - ID: "a2b8abdd-d8aa-49f4-b3dd-27fea3f7da6e"
      Hint: PageTitle
      Value: Nabídka
