---
ID: "92f56301-b3dd-47fa-91e6-8752d8ebbbe1"
Parent: "212c0d14-4bdf-47a6-846a-cdf7a549b169"
Template: "212c0d14-4bdf-47a6-846a-cdf7a549b169"
Path: /sitecore/templates/eContracting2/WebRoot/__Standard Values
DB: master
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Type: TreelistEx
  Value: 
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 300
Languages:
- Language: cs
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200908T082439Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
